[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "geolocation=(self \"https://bucolic-concha-b3e289.netlify.app\")"
    accelerometer = "(self \"https://bucolic-concha-b3e289.netlify.app\")"
    gyroscope = "(self \"https://bucolic-concha-b3e289.netlify.app\")"
    magnetometer = "(self \"https://bucolic-concha-b3e289.netlify.app\")"
    device-orientation = "(self \"https://bucolic-concha-b3e289.netlify.app\")"
