[[headers]]
  for = "/*" # Aplica estas cabeceras a todas las rutas de este sitio de Netlify (el mapa)
  [headers.values]
    # Esta política permite la geolocalización para el propio dominio del mapa ('self')
    # Y lo más importante: permite que la geolocalización se use si el iframe es cargado
    # por CUALQUIER origen ('*'). Esta es la política más permisiva para iframes.
    Permissions-Policy = "geolocation=(self *)"
    # Añadimos también las políticas para los sensores de movimiento, ya que la consola los menciona.
    accelerometer = "(self *)"
    gyroscope = "(self *)"
    magnetometer = "(self *)"
    device-orientation = "(self *)"
